/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScannerIndexRouteImport } from './routes/scanner/index'
import { Route as ParentIndexRouteImport } from './routes/parent/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ScannerSettingsRouteImport } from './routes/scanner/settings'
import { Route as ParentTrackingRouteImport } from './routes/parent/tracking'
import { Route as ParentSettingsRouteImport } from './routes/parent/settings'
import { Route as ParentProfilesRouteImport } from './routes/parent/profiles'
import { Route as ParentAttendanceRouteImport } from './routes/parent/attendance'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminFaceRegistrationRouteImport } from './routes/admin/face-registration'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminDepartmentsIndexRouteImport } from './routes/admin/departments/index'
import { Route as AdminBusesIndexRouteImport } from './routes/admin/buses/index'
import { Route as AdminAttendanceIndexRouteImport } from './routes/admin/attendance/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminStudentsStudentIdRouteImport } from './routes/admin/students/$studentId'
import { Route as AdminDepartmentsDeptIdRouteImport } from './routes/admin/departments/$deptId'
import { Route as AdminBusesBusIdRouteImport } from './routes/admin/buses/$busId'
import { Route as AdminAttendanceTodayRouteImport } from './routes/admin/attendance/today'
import { Route as AdminAttendanceDateRouteImport } from './routes/admin/attendance/$date'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerIndexRoute = ScannerIndexRouteImport.update({
  id: '/scanner/',
  path: '/scanner/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ScannerSettingsRoute = ScannerSettingsRouteImport.update({
  id: '/scanner/settings',
  path: '/scanner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentTrackingRoute = ParentTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSettingsRoute = ParentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ParentRoute,
} as any)
const ParentProfilesRoute = ParentProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAttendanceRoute = ParentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ParentRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaceRegistrationRoute = AdminFaceRegistrationRouteImport.update({
  id: '/face-registration',
  path: '/face-registration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsIndexRoute = AdminDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusesIndexRoute = AdminBusesIndexRouteImport.update({
  id: '/buses/',
  path: '/buses/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceIndexRoute = AdminAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsStudentIdRoute = AdminStudentsStudentIdRouteImport.update({
  id: '/students/$studentId',
  path: '/students/$studentId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsDeptIdRoute = AdminDepartmentsDeptIdRouteImport.update({
  id: '/departments/$deptId',
  path: '/departments/$deptId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusesBusIdRoute = AdminBusesBusIdRouteImport.update({
  id: '/buses/$busId',
  path: '/buses/$busId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceTodayRoute = AdminAttendanceTodayRouteImport.update({
  id: '/attendance/today',
  path: '/attendance/today',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceDateRoute = AdminAttendanceDateRouteImport.update({
  id: '/attendance/$date',
  path: '/attendance/$date',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/face-registration': typeof AdminFaceRegistrationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/profiles': typeof ParentProfilesRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/tracking': typeof ParentTrackingRoute
  '/scanner/settings': typeof ScannerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/scanner/': typeof ScannerIndexRoute
  '/admin/attendance/$date': typeof AdminAttendanceDateRoute
  '/admin/attendance/today': typeof AdminAttendanceTodayRoute
  '/admin/buses/$busId': typeof AdminBusesBusIdRoute
  '/admin/departments/$deptId': typeof AdminDepartmentsDeptIdRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/attendance/': typeof AdminAttendanceIndexRoute
  '/admin/buses/': typeof AdminBusesIndexRoute
  '/admin/departments/': typeof AdminDepartmentsIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/face-registration': typeof AdminFaceRegistrationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/profiles': typeof ParentProfilesRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/tracking': typeof ParentTrackingRoute
  '/scanner/settings': typeof ScannerSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/parent': typeof ParentIndexRoute
  '/scanner': typeof ScannerIndexRoute
  '/admin/attendance/$date': typeof AdminAttendanceDateRoute
  '/admin/attendance/today': typeof AdminAttendanceTodayRoute
  '/admin/buses/$busId': typeof AdminBusesBusIdRoute
  '/admin/departments/$deptId': typeof AdminDepartmentsDeptIdRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/attendance': typeof AdminAttendanceIndexRoute
  '/admin/buses': typeof AdminBusesIndexRoute
  '/admin/departments': typeof AdminDepartmentsIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/parent': typeof ParentRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/face-registration': typeof AdminFaceRegistrationRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/profiles': typeof ParentProfilesRoute
  '/parent/settings': typeof ParentSettingsRoute
  '/parent/tracking': typeof ParentTrackingRoute
  '/scanner/settings': typeof ScannerSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/scanner/': typeof ScannerIndexRoute
  '/admin/attendance/$date': typeof AdminAttendanceDateRoute
  '/admin/attendance/today': typeof AdminAttendanceTodayRoute
  '/admin/buses/$busId': typeof AdminBusesBusIdRoute
  '/admin/departments/$deptId': typeof AdminDepartmentsDeptIdRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/attendance/': typeof AdminAttendanceIndexRoute
  '/admin/buses/': typeof AdminBusesIndexRoute
  '/admin/departments/': typeof AdminDepartmentsIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/parent'
    | '/signup'
    | '/admin/face-registration'
    | '/admin/settings'
    | '/parent/attendance'
    | '/parent/profiles'
    | '/parent/settings'
    | '/parent/tracking'
    | '/scanner/settings'
    | '/admin/'
    | '/parent/'
    | '/scanner/'
    | '/admin/attendance/$date'
    | '/admin/attendance/today'
    | '/admin/buses/$busId'
    | '/admin/departments/$deptId'
    | '/admin/students/$studentId'
    | '/admin/users/$userId'
    | '/admin/attendance/'
    | '/admin/buses/'
    | '/admin/departments/'
    | '/admin/students/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/face-registration'
    | '/admin/settings'
    | '/parent/attendance'
    | '/parent/profiles'
    | '/parent/settings'
    | '/parent/tracking'
    | '/scanner/settings'
    | '/admin'
    | '/parent'
    | '/scanner'
    | '/admin/attendance/$date'
    | '/admin/attendance/today'
    | '/admin/buses/$busId'
    | '/admin/departments/$deptId'
    | '/admin/students/$studentId'
    | '/admin/users/$userId'
    | '/admin/attendance'
    | '/admin/buses'
    | '/admin/departments'
    | '/admin/students'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/parent'
    | '/signup'
    | '/admin/face-registration'
    | '/admin/settings'
    | '/parent/attendance'
    | '/parent/profiles'
    | '/parent/settings'
    | '/parent/tracking'
    | '/scanner/settings'
    | '/admin/'
    | '/parent/'
    | '/scanner/'
    | '/admin/attendance/$date'
    | '/admin/attendance/today'
    | '/admin/buses/$busId'
    | '/admin/departments/$deptId'
    | '/admin/students/$studentId'
    | '/admin/users/$userId'
    | '/admin/attendance/'
    | '/admin/buses/'
    | '/admin/departments/'
    | '/admin/students/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ParentRoute: typeof ParentRouteWithChildren
  SignupRoute: typeof SignupRoute
  ScannerSettingsRoute: typeof ScannerSettingsRoute
  ScannerIndexRoute: typeof ScannerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner/': {
      id: '/scanner/'
      path: '/scanner'
      fullPath: '/scanner/'
      preLoaderRoute: typeof ScannerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/scanner/settings': {
      id: '/scanner/settings'
      path: '/scanner/settings'
      fullPath: '/scanner/settings'
      preLoaderRoute: typeof ScannerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/tracking': {
      id: '/parent/tracking'
      path: '/tracking'
      fullPath: '/parent/tracking'
      preLoaderRoute: typeof ParentTrackingRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/settings': {
      id: '/parent/settings'
      path: '/settings'
      fullPath: '/parent/settings'
      preLoaderRoute: typeof ParentSettingsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/profiles': {
      id: '/parent/profiles'
      path: '/profiles'
      fullPath: '/parent/profiles'
      preLoaderRoute: typeof ParentProfilesRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/attendance': {
      id: '/parent/attendance'
      path: '/attendance'
      fullPath: '/parent/attendance'
      preLoaderRoute: typeof ParentAttendanceRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/face-registration': {
      id: '/admin/face-registration'
      path: '/face-registration'
      fullPath: '/admin/face-registration'
      preLoaderRoute: typeof AdminFaceRegistrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments/': {
      id: '/admin/departments/'
      path: '/departments'
      fullPath: '/admin/departments/'
      preLoaderRoute: typeof AdminDepartmentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buses/': {
      id: '/admin/buses/'
      path: '/buses'
      fullPath: '/admin/buses/'
      preLoaderRoute: typeof AdminBusesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance/': {
      id: '/admin/attendance/'
      path: '/attendance'
      fullPath: '/admin/attendance/'
      preLoaderRoute: typeof AdminAttendanceIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students/$studentId': {
      id: '/admin/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminStudentsStudentIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments/$deptId': {
      id: '/admin/departments/$deptId'
      path: '/departments/$deptId'
      fullPath: '/admin/departments/$deptId'
      preLoaderRoute: typeof AdminDepartmentsDeptIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buses/$busId': {
      id: '/admin/buses/$busId'
      path: '/buses/$busId'
      fullPath: '/admin/buses/$busId'
      preLoaderRoute: typeof AdminBusesBusIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance/today': {
      id: '/admin/attendance/today'
      path: '/attendance/today'
      fullPath: '/admin/attendance/today'
      preLoaderRoute: typeof AdminAttendanceTodayRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance/$date': {
      id: '/admin/attendance/$date'
      path: '/attendance/$date'
      fullPath: '/admin/attendance/$date'
      preLoaderRoute: typeof AdminAttendanceDateRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFaceRegistrationRoute: typeof AdminFaceRegistrationRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAttendanceDateRoute: typeof AdminAttendanceDateRoute
  AdminAttendanceTodayRoute: typeof AdminAttendanceTodayRoute
  AdminBusesBusIdRoute: typeof AdminBusesBusIdRoute
  AdminDepartmentsDeptIdRoute: typeof AdminDepartmentsDeptIdRoute
  AdminStudentsStudentIdRoute: typeof AdminStudentsStudentIdRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminAttendanceIndexRoute: typeof AdminAttendanceIndexRoute
  AdminBusesIndexRoute: typeof AdminBusesIndexRoute
  AdminDepartmentsIndexRoute: typeof AdminDepartmentsIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFaceRegistrationRoute: AdminFaceRegistrationRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAttendanceDateRoute: AdminAttendanceDateRoute,
  AdminAttendanceTodayRoute: AdminAttendanceTodayRoute,
  AdminBusesBusIdRoute: AdminBusesBusIdRoute,
  AdminDepartmentsDeptIdRoute: AdminDepartmentsDeptIdRoute,
  AdminStudentsStudentIdRoute: AdminStudentsStudentIdRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminAttendanceIndexRoute: AdminAttendanceIndexRoute,
  AdminBusesIndexRoute: AdminBusesIndexRoute,
  AdminDepartmentsIndexRoute: AdminDepartmentsIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParentRouteChildren {
  ParentAttendanceRoute: typeof ParentAttendanceRoute
  ParentProfilesRoute: typeof ParentProfilesRoute
  ParentSettingsRoute: typeof ParentSettingsRoute
  ParentTrackingRoute: typeof ParentTrackingRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAttendanceRoute: ParentAttendanceRoute,
  ParentProfilesRoute: ParentProfilesRoute,
  ParentSettingsRoute: ParentSettingsRoute,
  ParentTrackingRoute: ParentTrackingRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ParentRoute: ParentRouteWithChildren,
  SignupRoute: SignupRoute,
  ScannerSettingsRoute: ScannerSettingsRoute,
  ScannerIndexRoute: ScannerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
